Repository procrastinate-org/procrastinate, pull requests merged in 2020-09, with the labels that each got.

#310 Fix the demo
  procrastinate_demo/__main__.py
  procrastinate_demo/app.py
Labels: PR type: miscellaneous, PR: Skip changelog

#302 GitHub actions
  .github/workflows/main.yml
Labels: PR scope: incremental, PR type: miscellaneous

#311 Run the main workflow for other branches than master
  .github/workflows/main.yml
Labels: PR scope: minor, PR type: miscellaneous

#308 Use migra instead of pum for the db migration tests
  CONTRIBUTING.rst
  docs/howto/migrations.rst
  docs/howto/pum.rst
  docs/howto_index.rst
  docs/spelling_wordlist.txt
  setup.cfg
  tests/migration/test_migration.py
Labels: PR scope: incremental, PR type: miscellaneous

#315 Use postgres:12 image for faster tests
  .github/workflows/main.yml
  docker-compose.yml
Labels: PR scope: incremental, PR type: miscellaneous, Type: Process

#316 Set postgres fsync to off in docker-compose.yml
  docker-compose.yml
Labels: PR: Skip changelog

#317 Make test_run_log_current_job_when_stopping more robust
  tests/integration/test_worker.py
Labels: PR scope: incremental, PR type: miscellaneous

#319 Use setuptools-scm to get migration from Git
  .github/workflows/main.yml
  pyproject.toml
  setup.py
Labels: PR scope: incremental, PR type: miscellaneous
