Repository procrastinate-org/procrastinate, pull requests merged in 2020-06, with the labels that each got.

#236 Create "set pool" lock lazily
  procrastinate/aiopg_connector.py
Labels: PR:bugfix, PR:incremental

#239 Add a github action to get automated changelogs
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  CONTRIBUTING.rst
Labels: PR:incremental, PR:miscellaneous

#243 Improve release-drafter settings
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter.yml
Labels: PR scope: incremental, PR type: miscellaneous, Type: Process

#245 Update release-drafter.yml
  .github/release-drafter.yml
Labels: PR scope: incremental, PR type: miscellaneous

#248 CONTRIBUTING.rst: more precise wording on release automated steps
  CONTRIBUTING.rst
Labels: PR scope: incremental, PR type: miscellaneous

#231 Close race condition in procrastinate_fetch_job
  docs/discussions.rst
  procrastinate/sql/migrations/delta_0.9.0_001_close_fetch_job_race_condition.sql
  procrastinate/sql/schema.sql
Labels: PR scope: incremental, PR type: bugfix

#237 Sync connector 225
  CONTRIBUTING.rst
  docs/discussions.rst
  docs/howto/connector.rst
  docs/howto/middleware.rst
  docs/howto/sync_defer.rst
  docs/howto_index.rst
  docs/reference.rst
  docs/spelling_wordlist.txt
  procrastinate/__init__.py
  procrastinate/admin.py
  procrastinate/aiopg_connector.py
  procrastinate/app.py
  procrastinate/cli.py
  procrastinate/connector.py
  procrastinate/exceptions.py
  procrastinate/healthchecks.py
  procrastinate/jobs.py
  procrastinate/psycopg2_connector.py
  procrastinate/schema.py
  procrastinate/store.py
  procrastinate/testing.py
  procrastinate/utils.py
  procrastinate_demo/app.py
  setup.cfg
  tests/acceptance/app.py
  tests/acceptance/conftest.py
  tests/acceptance/test_async.py
  tests/acceptance/test_nominal.py
  tests/conftest.py
  tests/integration/test_admin.py
  tests/integration/test_aiopg_connector.py
  tests/integration/test_healthchecks.py
  tests/integration/test_psycopg2_connector.py
  tests/integration/test_store.py
  tests/integration/test_wait_stop.py
  tests/unit/test_aiopg_connector.py
  tests/unit/test_cli.py
  tests/unit/test_connector.py
  tests/unit/test_psycopg2_connector.py
  tests/unit/test_store.py
  tests/unit/test_testing.py
  tests/unit/test_worker.py
Labels: PR scope: minor, PR type: feature

#250 Rename migration scripts
  procrastinate/sql/migrations/delta_0.10.0_001_close_fetch_job_race_condition.sql
  procrastinate/sql/migrations/delta_0.10.0_002_add_defer_job_function.sql
Labels: PR: Skip changelog

#253 Display test results & simplify Tox setup
  .travis.yml
  setup.cfg
  tox.ini
Labels: PR scope: incremental, PR type: miscellaneous

#252 Default log message contains task result
  procrastinate/worker.py
  procrastinate_demo/tasks.py
  tests/acceptance/test_nominal.py
  tests/unit/test_worker.py
Labels: PR scope: incremental, PR type: feature

#257 Add task.defer as an explicit sync method
  procrastinate/tasks.py
  tests/acceptance/test_sync.py
Labels: PR scope: incremental, PR type: bugfix

#258 Make listen/notify optional
  docs/discussions.rst
  docs/howto/connections.rst
  docs/howto/connector.rst
  docs/howto_index.rst
  procrastinate/aiopg_connector.py
  procrastinate/app.py
  procrastinate/cli.py
  procrastinate/worker.py
  tests/integration/test_cli.py
  tests/integration/test_worker.py
  tests/unit/test_aiopg_connector.py
Labels: PR scope: minor, PR type: breaking

#259 Retry on "server closed connection unexpectedly" errors
  procrastinate/aiopg_connector.py
  procrastinate/psycopg2_connector.py
  tests/integration/test_aiopg_connector.py
  tests/integration/test_psycopg2_connector.py
  tests/unit/test_aiopg_connector.py
  tests/unit/test_psycopg2_connector.py
Labels: PR scope: incremental, PR type: feature, Type: Feature

#261 Improve wording of wrap_query_exceptions docstring
  procrastinate/aiopg_connector.py
  procrastinate/psycopg2_connector.py
Labels: PR: Skip changelog

#254 Quickstart
  docs/quickstart.rst
  procrastinate/cli.py
  procrastinate/connector.py
  procrastinate/tasks.py
  procrastinate/utils.py
  tests/acceptance/test_nominal.py
  tests/unit/test_utils.py
Labels: PR scope: incremental, PR type: bugfix, PR type: miscellaneous

#263 Synchronous closing for AiopgConnector
  procrastinate/aiopg_connector.py
  procrastinate_demo/__main__.py
  tests/integration/test_aiopg_connector.py
Labels: PR scope: incremental, PR type: bugfix

#266 Docs
  .readthedocs.yml
  MANIFEST.in
  setup.cfg
Labels: PR scope: incremental, PR type: bugfix

#267 Fix changelog script: skip draft releases
  docs/sphinxext/changelog.py
Labels: PR scope: incremental, PR type: miscellaneous

#268 Typo
  docs/howto/connections.rst
Labels: PR: Skip changelog
