Repository procrastinate-org/procrastinate, pull requests merged in 2020-08, with the labels that each got.

#293 Fix the "every second periodic task" bug
  procrastinate/periodic.py
  tests/acceptance/app.py
  tests/acceptance/test_nominal.py
  tests/unit/test_periodic.py
Labels: PR scope: incremental, PR type: bugfix

#291 Additional doc on periodic tasks
  CONTRIBUTING.rst
  docs/discussions.rst
  docs/howto/cron.rst
  docs/howto/locks.rst
  docs/spelling_wordlist.txt
  procrastinate/sql/migrations/baseline-0.5.0.sql
  procrastinate/sql/schema.sql
  procrastinate_demo/app.py
Labels: PR scope: incremental, PR type: miscellaneous

#294 Additional doc on periodic tasks - forgotten wording fix
  docs/howto/cron.rst
Labels: PR scope: incremental, PR type: miscellaneous

#299 Badges
  README.rst
Labels: PR scope: incremental, PR type: miscellaneous

#306 Update codebase with black's new trailing commas rule
  procrastinate/admin.py
  procrastinate/aiopg_connector.py
  procrastinate/cli.py
  procrastinate/periodic.py
  procrastinate/psycopg2_connector.py
  procrastinate/store.py
  procrastinate/worker.py
  setup.cfg
  tests/conftest.py
  tests/unit/test_aiopg_connector.py
  tests/unit/test_app.py
  tests/unit/test_retry.py
  tests/unit/test_shell.py
  tests/unit/test_sql.py
  tests/unit/test_utils.py
  tests/unit/test_worker.py
Labels: PR: Skip changelog, Type: Refactor
