Repository procrastinate-org/procrastinate, pull requests merged in 2020-07, with the labels that each got.

#240 Add a periodic task (cron) system
  docs/glossary.rst
  docs/howto/cron.rst
  docs/howto/locks.rst
  docs/howto/queueing_locks.rst
  docs/howto_index.rst
  procrastinate/app.py
  procrastinate/periodic.py
  procrastinate/sql/migrations/delta_0.11.0_003_add_procrastinate_periodic_defers.sql
  procrastinate/sql/queries.sql
  procrastinate/sql/schema.sql
  procrastinate/store.py
  procrastinate/testing.py
  procrastinate/utils.py
  procrastinate/worker.py
  procrastinate_demo/app.py
  procrastinate_demo/tasks.py
  setup.cfg
  tests/acceptance/app.py
  tests/acceptance/conftest.py
  tests/acceptance/test_nominal.py
  tests/acceptance/test_shell.py
  tests/unit/test_app.py
  tests/unit/test_periodic.py
  tests/unit/test_store.py
  tests/unit/test_utils.py
  tests/unit/test_worker.py
Labels: PR scope: minor, PR type: feature

#274 Clarify that current release draft is unreleased
  .github/release-drafter.yml
Labels: PR: Skip changelog

#275 Adapt to new isort 5
  procrastinate/cli.py
  setup.cfg
  tests/unit/test_cli.py
  tox.ini
Labels: PR scope: incremental, PR type: miscellaneous

#277 Add missing index to procrastinate_periodic_defers
  procrastinate/sql/migrations/delta_0.12.0_001_add_foreign_key_index.sql
  procrastinate/sql/schema.sql
Labels: PR scope: incremental, PR type: bugfix

#279 Use python-dateutil to parse date
  docs/howto/schedule.rst
  procrastinate/cli.py
  procrastinate/retry.py
  procrastinate/tasks.py
  procrastinate/testing.py
  procrastinate/utils.py
  setup.cfg
  tests/conftest.py
  tests/integration/test_store.py
  tests/unit/test_app.py
  tests/unit/test_jobs.py
  tests/unit/test_retry.py
  tests/unit/test_store.py
  tests/unit/test_tasks.py
  tests/unit/test_testing.py
  tests/unit/test_utils.py
  tests/unit/test_worker.py
Labels: Contains: Only Python, PR scope: minor, PR type: breaking, PR type: miscellaneous, Type: Refactor

#281 Fix demo code
  procrastinate_demo/app.py
Labels: PR: Skip changelog

#284 Dev env script
  CONTRIBUTING.rst
  MANIFEST.in
  dev-env
  setup.cfg
Labels: PR scope: incremental, PR type: miscellaneous
