Repository procrastinate-org/procrastinate, pull requests merged in 2024-08, with the labels that each got.

#1146 feat: allow cleaning of cancelled and aborted jobs
  docs/howto/production/delete_finished_jobs.md
  procrastinate/builtin_tasks.py
  procrastinate/manager.py
  tests/unit/test_builtin_tasks.py
Labels: PR type: feature ⭐️

#1114 refactor worker
  docs/discussions.md
  docs/howto/advanced.md
  docs/howto/advanced/shutdown.md
  docs/howto/basics/worker.md
  procrastinate/app.py
  procrastinate/builtin_tasks.py
  procrastinate/cli.py
  procrastinate/contrib/django/settings.py
  procrastinate/exceptions.py
  procrastinate/job_context.py
  procrastinate/jobs.py
  procrastinate/utils.py
  procrastinate/worker.py
  tests/acceptance/test_async.py
  tests/acceptance/test_nominal.py
  tests/conftest.py
  tests/integration/test_cli.py
  tests/integration/test_wait_stop.py
  tests/integration/test_worker.py
  tests/unit/test_app.py
  tests/unit/test_blueprints.py
  tests/unit/test_builtin_tasks.py
  tests/unit/test_cli.py
  tests/unit/test_job_context.py
  tests/unit/test_utils.py
  tests/unit/test_worker.py
  tests/unit/test_worker_sync.py
Labels: PR type: breaking 💥, PR type: feature ⭐️, PR type: documentation 📚

#1140 Make django Admin interface support slightly better UX wise
  procrastinate/contrib/django/admin.py
  procrastinate/contrib/django/migrations/0030_alter_procrastinateevent_options.py
  procrastinate/contrib/django/models.py
  procrastinate/contrib/django/templates/procrastinate/admin/summary.html
  tests/acceptance/django_settings.py
  tests/integration/contrib/django/test_models.py
  tests/unit/contrib/django/test_admin.py
Labels: PR type: miscellaneous 👾

#1139 Use additional abort field on jobs table for abortion requests
  procrastinate/contrib/django/migrations/0030_add_abort_on_procrastinate_jobs.py
  procrastinate/contrib/django/models.py
  procrastinate/job_context.py
  procrastinate/jobs.py
  procrastinate/manager.py
  procrastinate/shell.py
  procrastinate/sql/migrations/02.09.02_01_add_abort_on_procrastinate_jobs.sql
  procrastinate/sql/queries.sql
  procrastinate/sql/schema.sql
  procrastinate/testing.py
  procrastinate/worker.py
  tests/acceptance/test_async.py
  tests/acceptance/test_shell.py
  tests/integration/contrib/django/test_models.py
  tests/integration/test_cli.py
  tests/integration/test_manager.py
  tests/unit/test_jobs.py
  tests/unit/test_manager.py
  tests/unit/test_shell.py
  tests/unit/test_tasks.py
  tests/unit/test_testing.py
Labels: PR type: breaking 💥, PR type: bugfix 🕵️

#1152 Add sphinx extension
  .pre-commit-config.yaml
  docs/conf.py
  docs/howto/advanced.md
  docs/howto/advanced/sphinx.md
  poetry.lock
  procrastinate/contrib/sphinx/__init__.py
  procrastinate_demos/demo_async/tasks.py
  pyproject.toml
  tests/conftest.py
  tests/integration/contrib/sphinx/__init__.py
  tests/integration/contrib/sphinx/conftest.py
  tests/integration/contrib/sphinx/test-root/conf.py
  tests/integration/contrib/sphinx/test-root/index.rst
  tests/integration/contrib/sphinx/test_autodoc.py
Labels: PR type: bugfix 🕵️

#1160 Run sync task in its own thread
  procrastinate/utils.py
  tests/acceptance/test_sync.py
Labels: PR type: bugfix 🕵️

#1162 Wrap Django exceptions correctly
  .pre-commit-config.yaml
  poetry.lock
  procrastinate/contrib/django/django_connector.py
  pyproject.toml
  tests/integration/contrib/django/test_django_connector.py
  tests/unit/contrib/django/test_django_connector.py
Labels: PR type: bugfix 🕵️

#1163 Add Kai Schlamp as an author
  docs/conf.py
  pyproject.toml
Labels: PR type: miscellaneous 👾

#1159 Async InMemoryConnector (testing)
  procrastinate/testing.py
  tests/conftest.py
  tests/integration/test_cli.py
  tests/unit/test_job_context.py
  tests/unit/test_manager.py
  tests/unit/test_shell.py
  tests/unit/test_testing.py
  tests/unit/test_worker.py
Labels: PR type: miscellaneous 👾

#1153 Remove sphinx-autodoc-typehints, upgrade Myst & Sphinx
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  .readthedocs.yml
  dev-env
  docs/conf.py
  docs/reference.rst
  poetry.lock
  procrastinate/app.py
  procrastinate/blueprints.py
  procrastinate/builtin_tasks.py
  procrastinate/contrib/aiopg/aiopg_connector.py
  procrastinate/contrib/django/django_connector.py
  procrastinate/contrib/django/utils.py
  procrastinate/contrib/psycopg2/psycopg2_connector.py
  procrastinate/job_context.py
  procrastinate/jobs.py
  procrastinate/manager.py
  procrastinate/retry.py
  procrastinate/tasks.py
  procrastinate/testing.py
  pyproject.toml
Labels: PR type: documentation 📚

#1164 Fix Django + cron using the wrong connector
  docs/howto/advanced/sync_defer.md
  docs/howto/django/scripts.md
  docs/howto/django/tests.md
  docs/howto/production/testing.md
  procrastinate/app.py
  procrastinate/contrib/django/management/commands/procrastinate.py
  tests/integration/contrib/django/test_models.py
Labels: PR type: bugfix 🕵️

#1168 Rename remove_error and include_error to remove_failed and include_failed
  docs/howto/production/delete_finished_jobs.md
  procrastinate/builtin_tasks.py
  procrastinate/manager.py
  tests/integration/test_manager.py
  tests/unit/test_builtin_tasks.py
  tests/unit/test_manager.py
Labels: PR type: breaking 💥

#1174 Improve task and defer docs
  docs/howto/basics/defer.md
  docs/howto/basics/tasks.md
Labels: PR type: documentation 📚
