Repository procrastinate-org/procrastinate, pull requests merged in 2024-02, with the labels that each got.

#921 Django: PROCRASTINATE_ON_APP_READY
  docs/howto/django.md
  procrastinate/contrib/django/apps.py
  tests/unit/contrib/django/test_apps.py
Labels: PR type: feature ⭐️

#922 Fix doc
  docs/howto/django.md
  scripts/docs
Labels: PR type: documentation 📚

#924 Update max_delay description
  procrastinate/app.py
Labels: PR type: documentation 📚

#945 Django demo uses transaction.atomic()
  procrastinate_demos/demo_django/demo/tasks.py
Labels: PR type: miscellaneous 👾

#946 DjangoConnector.get_worker_connector() uses psycopg3 if available
  .readthedocs.yml
  docs/howto/django.md
  procrastinate/contrib/django/django_connector.py
  procrastinate/contrib/django/utils.py
  tests/integration/contrib/django/test_django_connector.py
  tests/unit/contrib/django/test_utils.py
Labels: PR type: bugfix 🕵️

#950 Fix import in Django connector
  procrastinate/contrib/django/django_connector.py
Labels: PR type: bugfix 🕵️

#953 Fix doc (wrong method)
  docs/howto/django.md
Labels: PR type: documentation 📚

#954 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR type: miscellaneous 👾

#955 Add explicit error message if users use the django app before .ready()
  docs/howto/django.md
  procrastinate/app.py
  procrastinate/blueprints.py
  procrastinate/contrib/django/__init__.py
  procrastinate/contrib/django/exceptions.py
  procrastinate/contrib/django/placeholder.py
  procrastinate/tasks.py
  tests/unit/contrib/django/test_placeholder.py
Labels: PR type: bugfix 🕵️
