Repository procrastinate-org/procrastinate, pull requests merged in 2024-09, with the labels that each got.

#1179 Fix GitHub's upload-artifact breakage
  .github/workflows/ci.yml
Labels: PR type: miscellaneous 👾

#1172 Add support for abort notification
  docs/discussions.md
  docs/howto/advanced/cancellation.md
  procrastinate/app.py
  procrastinate/connector.py
  procrastinate/contrib/aiopg/aiopg_connector.py
  procrastinate/contrib/django/django_connector.py
  procrastinate/contrib/django/migrations/0032_cancel_notification.py
  procrastinate/contrib/django/models.py
  procrastinate/job_context.py
  procrastinate/jobs.py
  procrastinate/manager.py
  procrastinate/psycopg_connector.py
  procrastinate/sql/migrations/03.00.00_01_cancel_notification.sql
  procrastinate/sql/queries.sql
  procrastinate/sql/schema.sql
  procrastinate/testing.py
  procrastinate/utils.py
  procrastinate/worker.py
  tests/acceptance/test_async.py
  tests/conftest.py
  tests/integration/contrib/aiopg/conftest.py
  tests/integration/contrib/aiopg/test_aiopg_connector.py
  tests/integration/contrib/django/test_models.py
  tests/integration/test_psycopg_connector.py
  tests/unit/test_app.py
  tests/unit/test_builtin_tasks.py
  tests/unit/test_connector.py
  tests/unit/test_job_context.py
  tests/unit/test_jobs.py
  tests/unit/test_manager.py
  tests/unit/test_testing.py
  tests/unit/test_worker.py
  tests/unit/test_worker_sync.py
Labels: PR type: breaking 💥, PR type: feature ⭐️

#1190 Abort async tasks using asyncio
  docs/howto/advanced/cancellation.md
  procrastinate/worker.py
  tests/acceptance/test_async.py
  tests/unit/test_worker.py
Labels: PR type: feature ⭐️

#1191 Add page to docs about job relationships in Django
  docs/howto/django.md
  docs/howto/django/related.md
Labels: PR type: documentation 📚

#1197 Make recent Python versions use recent Django versions
  .pre-commit-config.yaml
  docs/howto/django/configuration.md
  poetry.lock
  pyproject.toml
Labels: PR type: dependencies 🤖

#1196 Add return type informations for decorated tasks
  procrastinate/blueprints.py
  procrastinate/periodic.py
  procrastinate/tasks.py
Labels: PR type: miscellaneous 👾

#1192 Abort job polling interval
  docs/discussions.md
  docs/howto/advanced/cancellation.md
  procrastinate/app.py
  procrastinate/cli.py
  procrastinate/worker.py
  tests/acceptance/test_async.py
  tests/integration/test_cli.py
  tests/integration/test_wait_stop.py
  tests/unit/test_app.py
  tests/unit/test_worker.py
Labels: PR type: feature ⭐️, PR type: documentation 📚

#1202 Make docs dependencies non optional again
  dev-env
  poetry.lock
  pyproject.toml
Labels: PR type: dependencies 🤖

#1204 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: PR type: documentation 📚
