Repository procrastinate-org/procrastinate, pull requests merged in 2024-07, with the labels that each got.

#1098 [doc] context must be offered as positional argument
  docs/howto/production/delete_finished_jobs.md
Labels: PR type: documentation 📚

#1103 Deps updates
  .pre-commit-config.yaml
  poetry.lock
  procrastinate/psycopg_connector.py
  procrastinate/sync_psycopg_connector.py
Labels: PR type: dependencies 🤖

#1102 app.replace_connector to ease tests
  docs/howto/django/tests.md
  docs/howto/production/testing.md
  procrastinate/app.py
  procrastinate/contrib/django/procrastinate_app.py
  procrastinate/signals.py
  tests/unit/test_app.py
Labels: PR type: feature ⭐️

#1104 Remove duplicate documentation badge
  README.md
Labels: PR type: documentation 📚

#1107 Clarify verbosity
  docs/howto/django/basic_usage.md
  docs/howto/django/scripts.md
  procrastinate/contrib/django/management/commands/procrastinate.py
Labels: PR type: documentation 📚

#1117 Fix SchemaManager.apply_schema
  procrastinate/schema.py
  tests/integration/test_schema.py
Labels: PR type: bugfix 🕵️

#1113 Allow to change the priority of a to be retried job
  docs/howto/advanced/retry.md
  docs/reference.rst
  procrastinate/__init__.py
  procrastinate/contrib/django/migrations/0029_add_additional_params_to_retry_job.py
  procrastinate/exceptions.py
  procrastinate/manager.py
  procrastinate/retry.py
  procrastinate/sql/migrations/02.08.00_01_add_additional_params_to_retry_job.sql
  procrastinate/sql/queries.sql
  procrastinate/sql/schema.sql
  procrastinate/tasks.py
  procrastinate/testing.py
  procrastinate/types.py
  procrastinate/utils.py
  procrastinate/worker.py
  tests/integration/test_manager.py
  tests/unit/test_manager.py
  tests/unit/test_retry.py
  tests/unit/test_tasks.py
  tests/unit/test_testing.py
  tests/unit/test_worker.py
Labels: PR type: feature ⭐️

#1121 Can't use CLI parameters named args because of Django
  procrastinate/cli.py
  tests/unit/contrib/django/test_cli.py
  tests/unit/test_cli.py
Labels: PR type: bugfix 🕵️

#1128 exclude psycopg[binary] on mac arm64 python <=3.9
  poetry.lock
  pyproject.toml
Labels: PR type: dependencies 🤖

#1133 Set job to failed when task raises and job is aborting (regardless retry)
  docs/howto/advanced/cancellation.md
  procrastinate/worker.py
  tests/acceptance/test_async.py
  tests/unit/test_worker.py
Labels: PR type: bugfix 🕵️
