Repository procrastinate-org/procrastinate, pull requests merged in 2024-05, with the labels that each got.

#1057 test_get_sync_connector__[not]_open as integration test, not unit test
  tests/integration/contrib/aiopg/test_aiopg_connector.py
  tests/integration/test_psycopg_connector.py
  tests/unit/contrib/aiopg/test_aiopg_connector.py
  tests/unit/test_psycopg_connector.py
Labels: PR type: miscellaneous 👾

#1058 update django integration testing docs
  docs/howto/django/tests.md
Labels: PR type: documentation 📚

#1061 improve decorators type annotations
  procrastinate/blueprints.py
  procrastinate/periodic.py
  procrastinate/tasks.py
  tests/unit/test_app.py
  tests/unit/test_blueprints.py
  tests/unit/test_tasks.py
Labels: PR type: feature ⭐️
