Repository procrastinate-org/procrastinate, pull requests merged in 2024-10, with the labels that each got.

#1208 Add state graph (using mermaid) to the discussion page
  docs/conf.py
  docs/discussions.md
  poetry.lock
  pyproject.toml
Labels: PR type: documentation 📚

#1218 Fill missing generic type parameters for JobContext.task
  procrastinate/job_context.py
Labels: PR type: bugfix 🕵️, PR type: miscellaneous 👾

#1217 Respect the priority of a periodic task
  procrastinate/sql/queries.sql
  tests/acceptance/app.py
  tests/acceptance/test_nominal.py
Labels: PR type: bugfix 🕵️

#1213 Simplify job context
  docs/reference.rst
  procrastinate/job_context.py
  procrastinate/worker.py
  tests/unit/test_builtin_tasks.py
  tests/unit/test_job_context.py
Labels: PR type: breaking 💥

#1215 Shutdown timeout - abort sync tasks
  docs/howto/advanced/shutdown.md
  procrastinate/app.py
  procrastinate/cli.py
  procrastinate/job_context.py
  procrastinate/manager.py
  procrastinate/worker.py
  tests/acceptance/test_async.py
  tests/acceptance/test_sync.py
  tests/unit/test_app.py
  tests/unit/test_builtin_tasks.py
  tests/unit/test_job_context.py
  tests/unit/test_worker.py
Labels: PR type: feature ⭐️

#1224 Drop Python 3.8 support
  .pre-commit-config.yaml
  poetry.lock
  procrastinate/contrib/django/migrations_utils.py
  procrastinate/schema.py
  procrastinate/sql/__init__.py
  pyproject.toml
Labels: PR type: breaking 💥, PR type: dependencies 🤖

#1225 fix fetch job performance regression
  procrastinate/contrib/django/migrations/0031_add_indexes_for_fetch_job.py
  procrastinate/sql/migrations/02.14.01_01_add_indexes_for_fetch_job.sql
  procrastinate/sql/schema.sql
  tests/acceptance/test_async.py
Labels: PR type: bugfix 🕵️
