Repository procrastinate-org/procrastinate, pull requests merged in 2024-06, with the labels that each got.

#1071 Django Migrations are now created as normal files instead of being dynamically generated
  procrastinate/contrib/django/README.md
  procrastinate/contrib/django/apps.py
  procrastinate/contrib/django/migrations/0001_initial.py
  procrastinate/contrib/django/migrations/0002_drop_started_at_column.py
  procrastinate/contrib/django/migrations/0003_drop_started_at_column.py
  procrastinate/contrib/django/migrations/0004_drop_procrastinate_version_table.py
  procrastinate/contrib/django/migrations/0005_fix_procrastinate_fetch_job.py
  procrastinate/contrib/django/migrations/0006_fix_trigger_status_events_insert.py
  procrastinate/contrib/django/migrations/0007_add_queueing_lock_column.py
  procrastinate/contrib/django/migrations/0008_close_fetch_job_race_condition.py
  procrastinate/contrib/django/migrations/0009_add_defer_job_function.py
  procrastinate/contrib/django/migrations/0010_add_procrastinate_periodic_defers.py
  procrastinate/contrib/django/migrations/0011_add_foreign_key_index.py
  procrastinate/contrib/django/migrations/0012_add_locks_to_periodic_defer.py
  procrastinate/contrib/django/migrations/0013_fix_procrastinate_defer_periodic_job.py
  procrastinate/contrib/django/migrations/0014_add_finish_job_and_retry_job_functions.py
  procrastinate/contrib/django/migrations/0015_add_trigger_on_job_deletion.py
  procrastinate/contrib/django/migrations/0016_delete_finished_jobs.py
  procrastinate/contrib/django/migrations/0017_add_checks_to_finish_job.py
  procrastinate/contrib/django/migrations/0018_add_checks_to_retry_job.py
  procrastinate/contrib/django/migrations/0019_fix_finish_job_compat_issue.py
  procrastinate/contrib/django/migrations/0020_add_index_on_procrastinate_jobs.py
  procrastinate/contrib/django/migrations/0021_add_kwargs_to_defer_periodic_job.py
  procrastinate/contrib/django/migrations/0022_null_locks_excluded.py
  procrastinate/contrib/django/migrations/0023_remove_old_finish_job_function.py
  procrastinate/contrib/django/migrations/0024_job_id_bigint.py
  procrastinate/contrib/django/migrations/0025_add_models.py
  procrastinate/contrib/django/migrations/__init__.py
  procrastinate/contrib/django/migrations_magic.py
  procrastinate/contrib/django/migrations_utils.py
  procrastinate_demos/demo_django/demo/migrations/0001_initial.py
  pyproject.toml
  tests/unit/contrib/django/test_migrations.py
  tests/unit/contrib/django/test_migrations_magic.py
  tests/unit/contrib/django/test_migrations_utils.py
Labels: PR type: miscellaneous 👾

#1076 Failing test for pg_job_manager.delete_old_jobs with psycopg2-based lib
  procrastinate/sql/queries.sql
  tests/integration/contrib/aiopg/conftest.py
  tests/integration/contrib/aiopg/test_aiopg_connector.py
  tests/integration/contrib/aiopg/test_aiopg_job_manager.py
Labels: PR type: bugfix 🕵️

#1070 Add job priority feature
  docs/howto/advanced.md
  docs/howto/advanced/priorities.md
  procrastinate/cli.py
  procrastinate/contrib/django/migrations/0026_add_job_priority.py
  procrastinate/contrib/django/models.py
  procrastinate/jobs.py
  procrastinate/manager.py
  procrastinate/shell.py
  procrastinate/sql/migrations/02.00.03_01_add_job_priority.sql
  procrastinate/sql/queries.sql
  procrastinate/sql/schema.sql
  procrastinate/tasks.py
  procrastinate/testing.py
  tests/acceptance/test_nominal.py
  tests/acceptance/test_shell.py
  tests/integration/contrib/django/test_models.py
  tests/integration/test_cli.py
  tests/integration/test_psycopg_connector.py
  tests/unit/test_app.py
  tests/unit/test_cli.py
  tests/unit/test_jobs.py
  tests/unit/test_manager.py
  tests/unit/test_shell.py
  tests/unit/test_tasks.py
  tests/unit/test_testing.py
Labels: PR type: feature ⭐️

#1079 Allow to specify a default priority on the task
  docs/howto/advanced/priorities.md
  procrastinate/blueprints.py
  procrastinate/contrib/django/migrations/0027_add_periodic_job_priority.py
  procrastinate/manager.py
  procrastinate/sql/migrations/02.05.00_01_add_periodic_job_priority.sql
  procrastinate/sql/schema.sql
  procrastinate/tasks.py
  procrastinate/testing.py
  tests/acceptance/app.py
  tests/acceptance/test_nominal.py
  tests/unit/test_periodic.py
  tests/unit/test_tasks.py
Labels: PR type: feature ⭐️

#1078 Call configure callback in listen notify
  procrastinate/psycopg_connector.py
  tests/integration/test_psycopg_connector.py
Labels: PR type: miscellaneous 👾

#1081 Allow to cancel a job or request an abort
  docs/howto/advanced.md
  docs/howto/advanced/cancellation.md
  procrastinate/contrib/django/migrations/0028_add_cancel_states.py
  procrastinate/contrib/django/models.py
  procrastinate/exceptions.py
  procrastinate/job_context.py
  procrastinate/jobs.py
  procrastinate/manager.py
  procrastinate/shell.py
  procrastinate/sql/migrations/02.06.00_01_add_cancel_states.sql
  procrastinate/sql/queries.sql
  procrastinate/sql/schema.sql
  procrastinate/testing.py
  procrastinate/worker.py
  tests/acceptance/test_async.py
  tests/acceptance/test_shell.py
  tests/acceptance/test_sync.py
  tests/integration/test_manager.py
  tests/unit/test_job_context.py
  tests/unit/test_manager.py
  tests/unit/test_shell.py
  tests/unit/test_worker.py
Labels: PR type: breaking 💥, PR type: feature ⭐️

#1091 Remove deprecated file static_migrations.py
  procrastinate/contrib/django/static_migrations.py
Labels: PR type: miscellaneous 👾
