Repository procrastinate-org/procrastinate, pull requests merged in 2024-03, with the labels that each got.

#956 Fix psycopg3 detection
  docs/howto/django.md
  procrastinate/contrib/django/django_connector.py
  procrastinate/contrib/django/utils.py
  tests/integration/contrib/django/test_django_connector.py
  tests/unit/contrib/django/test_utils.py
Labels: PR type: bugfix 🕵️

#958 Add logs, evolve Django demo to use blueprints
  docs/howto/django.md
  docs/howto/logging.md
  procrastinate/blueprints.py
  procrastinate/worker.py
  procrastinate_demos/demo_django/demo/tasks.py
  procrastinate_demos/demo_django/project/settings.py
Labels: PR type: feature ⭐️, PR type: documentation 📚

#959 Make procrastinate.contrib.django.app a proxy
  procrastinate/contrib/django/__init__.py
  procrastinate/contrib/django/apps.py
  procrastinate/contrib/django/procrastinate_app.py
  tests/unit/contrib/django/test_placeholder.py
Labels: PR type: bugfix 🕵️

#962 Add missing documentation section in building changelog
  .github/release.yml
Labels: PR type: miscellaneous 👾

#960 Changes to the doc & django integration
  README.md
  docs/conf.py
  docs/howto/django.md
  docs/howto/django/basic_usage.md
  docs/howto/django/configuration.md
  docs/howto/django/logs.md
  docs/howto/django/migrations.md
  docs/howto/django/models.md
  docs/howto/django/scripts.md
  docs/howto/django/settings.md
  docs/howto/django/startup_actions.md
  docs/howto/django/tests.md
  docs/howto/migrations.md
  docs/howto/testing.md
  docs/howto_index.md
  procrastinate/contrib/django/__init__.py
  procrastinate/contrib/django/apps.py
  procrastinate/contrib/django/models.py
  procrastinate/contrib/django/placeholder.py
  procrastinate/contrib/django/procrastinate_app.py
  procrastinate/contrib/django/router.py
  procrastinate_demos/README.md
  tests/acceptance/django_settings.py
  tests/integration/contrib/django/test_models.py
Labels: PR type: documentation 📚

#968 Fix typo
  docs/howto/django/models.md
Labels: PR type: documentation 📚

#969 Reorganize howto doc into real sections
  docs/discussions.md
  docs/glossary.md
  docs/howto/advanced.md
  docs/howto/advanced/blueprints.md
  docs/howto/advanced/context.md
  docs/howto/advanced/cron.md
  docs/howto/advanced/custom_json_encoder_decoder.md
  docs/howto/advanced/events.md
  docs/howto/advanced/locks.md
  docs/howto/advanced/middleware.md
  docs/howto/advanced/queueing_locks.md
  docs/howto/advanced/retry.md
  docs/howto/advanced/schedule.md
  docs/howto/advanced/sync_defer.md
  docs/howto/basics.md
  docs/howto/basics/app.md
  docs/howto/basics/command_line.md
  docs/howto/basics/connector.md
  docs/howto/basics/defer.md
  docs/howto/basics/open_connection.md
  docs/howto/basics/tasks.md
  docs/howto/basics/worker.md
  docs/howto/django.md
  docs/howto/django/basic_usage.md
  docs/howto/django/logs.md
  docs/howto/django/migrations.md
  docs/howto/django/models.md
  docs/howto/production.md
  docs/howto/production/concurrency.md
  docs/howto/production/connections.md
  docs/howto/production/delete_finished_jobs.md
  docs/howto/production/deployment.md
  docs/howto/production/logging.md
  docs/howto/production/migrations.md
  docs/howto/production/monitoring.md
  docs/howto/production/retry_stalled_jobs.md
  docs/howto/production/schema.md
  docs/howto/production/testing.md
  docs/howto_index.md
  docs/quickstart.md
  procrastinate/app.py
  procrastinate/blueprints.py
Labels: PR type: documentation 📚

#970 Contributing doc adjustments
  CONTRIBUTING.md
Labels: PR type: documentation 📚

#971 Remove mention "but you can if you want to" from django config doc
  docs/howto/django/configuration.md
Labels: PR type: documentation 📚

#975 Fix Pyright
  .pre-commit-config.yaml
  procrastinate/cli.py
Labels: PR type: miscellaneous 👾

#976 provide manage.py procrastinate healthchecks
  docs/howto/django/basic_usage.md
  procrastinate/cli.py
  procrastinate/contrib/django/apps.py
  procrastinate/contrib/django/django_connector.py
  procrastinate/contrib/django/healthchecks.py
  procrastinate/contrib/django/management/commands/procrastinate.py
  procrastinate/contrib/django/models.py
  procrastinate/contrib/django/settings.py
  procrastinate/contrib/django/utils.py
  tests/integration/contrib/django/test_management_command.py
  tests/unit/contrib/django/test_settings.py
  tests/unit/contrib/django/test_utils.py
Labels: PR type: feature ⭐️

#985 Tie pyright version in GHA to pyright version in pre-commit
  .github/workflows/ci.yml
Labels: PR type: miscellaneous 👾

#980 fix: Typo
  docs/discussions.md
Labels: PR type: documentation 📚

#988 Update renovate rules
  .github/renovate.json5
Labels: PR type: miscellaneous 👾

#990 fix: Typo in django/configuration.md
  docs/howto/django/configuration.md
Labels: PR type: documentation 📚

#991 doc: Typo in django/basic_usage.md
  docs/howto/django/basic_usage.md
Labels: PR type: documentation 📚

#992 Update renovate.json5
  .github/renovate.json5
Labels: PR type: miscellaneous 👾

#1000 doc: Typo in blueprints.md
  docs/howto/advanced/blueprints.md
Labels: PR type: documentation 📚

#1001 doc: Typo in discussions.md
  docs/discussions.md
Labels: PR type: documentation 📚

#1002 Fix parsing of defer CLI command --at and --in options
  procrastinate/cli.py
  tests/integration/test_cli.py
  tests/unit/test_cli.py
Labels: PR type: bugfix 🕵️

#1012 Upgrade of asgiref brings a fix that means we exit the loop earlier
  poetry.lock
  tests/integration/test_worker.py
Labels: PR type: dependencies 🤖

#1013 Fix warnings, and enable warnings as errors in CI
  poetry.lock
  procrastinate/metadata.py
  pyproject.toml
  tests/integration/test_manager.py
  tests/migration/test_migration.py
Labels: PR type: bugfix 🕵️

#1014 Redo wrap_exception and add one for the Django Connector
  poetry.lock
  procrastinate/contrib/aiopg/aiopg_connector.py
  procrastinate/contrib/django/django_connector.py
  procrastinate/contrib/psycopg2/psycopg2_connector.py
  procrastinate/contrib/sqlalchemy/psycopg2_connector.py
  procrastinate/psycopg_connector.py
  procrastinate/sync_psycopg_connector.py
  procrastinate/utils.py
  pyproject.toml
  tests/integration/test_psycopg_connector.py
  tests/unit/contrib/aiopg/test_aiopg_connector.py
  tests/unit/contrib/psycopg2/test_psycopg2_connector.py
  tests/unit/contrib/sqlalchemy/test_psycopg2_connector.py
  tests/unit/test_psycopg_connector.py
  tests/unit/test_sync_psycopg_connector.py
  tests/unit/test_utils.py
Labels: PR type: bugfix 🕵️

#1015 Adding CI for py3.12 (facepalm)
  .github/workflows/ci.yml
Labels: PR type: miscellaneous 👾

#1016 Group renovate updates
  .github/renovate.json5
Labels: PR type: miscellaneous 👾

#1021 Renovate weekly (less noisy)
  .github/renovate.json5
Labels: PR type: miscellaneous 👾

#1023 Update renovate.json5
  .github/renovate.json5
Labels: PR type: miscellaneous 👾

#1024 Add psycopg pool factory
  docs/howto/basics/connector.md
  procrastinate/psycopg_connector.py
  tests/unit/test_psycopg_connector.py
Labels: PR type: feature ⭐️

#1025 doc: Fix typo in custom connection pool section
  docs/howto/basics/connector.md
Labels: PR type: documentation 📚
