Repository procrastinate-org/procrastinate, pull requests merged in 2025-03, with the labels that each got.

#1343 Only log Error level if all retry attempts fail( #1342)
  procrastinate/worker.py
  tests/unit/test_worker.py
Labels: PR type: feature ⭐️

#1347 Add some very simple benchmarks
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  .gitignore
  pyproject.toml
  tests/benchmarks/__init__.py
  tests/benchmarks/conftest.py
  tests/benchmarks/test_benchmark_async.py
  tests/benchmarks/test_benchmark_sync.py
  uv.lock
Labels: PR type: miscellaneous 👾

#1348 Add missing pytest's marker description
  pyproject.toml
Labels: PR type: miscellaneous 👾

#1351 doc fix
  docs/howto/advanced/middleware.md
Labels: PR type: documentation 📚

#1354 Adjust sleep times in test_stop_worker_aborts_sync_jobs_past_shutdown_graceful_timeout
  tests/acceptance/test_async.py
Labels: PR type: miscellaneous 👾

#1353 New rule for migration naming
  CONTRIBUTING.md
Labels: PR type: documentation 📚

#1355 Clean outdated skip-before-version
  tests/acceptance/test_async.py
  tests/acceptance/test_shell.py
Labels: PR type: miscellaneous 👾

#1344 Add heartbeats to detect stalled workers
  docs/howto/production/retry_stalled_jobs.md
  procrastinate/app.py
  procrastinate/contrib/django/migrations/0034_pre_add_heartbeat.py
  procrastinate/contrib/django/migrations/0035_post_add_heartbeat.py
  procrastinate/jobs.py
  procrastinate/manager.py
  procrastinate/sql/migrations/03.01.00_01_pre_add_heartbeat.sql
  procrastinate/sql/migrations/03.01.00_50_post_add_heartbeat.sql
  procrastinate/sql/queries.sql
  procrastinate/sql/schema.sql
  procrastinate/testing.py
  procrastinate/worker.py
  tests/integration/test_cli.py
  tests/integration/test_manager.py
  tests/unit/test_jobs.py
  tests/unit/test_manager.py
  tests/unit/test_shell.py
  tests/unit/test_tasks.py
  tests/unit/test_testing.py
  tests/unit/test_worker.py
Labels: PR type: feature ⭐️
