Repository procrastinate-org/procrastinate, pull requests merged in 2025-05, with the labels that each got.

#1377 Fix sync-pre-commit
  scripts/sync-pre-commit.py
Labels: PR type: bugfix 🕵️

#1378 Add a Django model for the worker
  procrastinate/contrib/django/migrations/0036_add_worker_model.py
  procrastinate/contrib/django/models.py
  tests/integration/contrib/django/test_models.py
Labels: PR type: miscellaneous 👾

#1371 Fix filepath typo in README.md
  README.md
Labels: PR type: bugfix 🕵️

#1382 Allow to batch defer multiple jobs at once
  docs/howto/basics.md
  docs/howto/basics/batch_defer.md
  docs/howto/basics/defer.md
  procrastinate/contrib/aiopg/aiopg_connector.py
  procrastinate/contrib/django/django_connector.py
  procrastinate/contrib/django/migrations/0037_pre_batch_defer_jobs.py
  procrastinate/contrib/django/migrations/0038_post_batch_defer_jobs.py
  procrastinate/contrib/psycopg2/psycopg2_connector.py
  procrastinate/contrib/sqlalchemy/psycopg2_connector.py
  procrastinate/exceptions.py
  procrastinate/jobs.py
  procrastinate/manager.py
  procrastinate/psycopg_connector.py
  procrastinate/sql/migrations/03.02.00_01_pre_batch_defer_jobs.sql
  procrastinate/sql/migrations/03.02.00_50_post_batch_defer_jobs.sql
  procrastinate/sql/queries.sql
  procrastinate/sql/schema.sql
  procrastinate/sync_psycopg_connector.py
  procrastinate/tasks.py
  procrastinate/testing.py
  procrastinate/types.py
  tests/acceptance/test_async.py
  tests/acceptance/test_sync.py
  tests/benchmarks/test_benchmark_async.py
  tests/benchmarks/test_benchmark_sync.py
  tests/integration/contrib/aiopg/test_aiopg_connector.py
  tests/integration/contrib/django/test_django_connector.py
  tests/integration/contrib/psycopg2/test_psycopg2_connector.py
  tests/integration/contrib/sqlalchemy/test_psycopg2_connector.py
  tests/integration/test_manager.py
  tests/integration/test_psycopg_connector.py
  tests/unit/test_manager.py
  tests/unit/test_shell.py
  tests/unit/test_sql.py
  tests/unit/test_tasks.py
  tests/unit/test_testing.py
  tests/unit/test_worker.py
Labels: PR type: feature ⭐️

#1388 Make the JSONValue type recursive
  .gitignore
  procrastinate/types.py
  procrastinate/worker.py
  tests/integration/test_manager.py
Labels: PR type: bugfix 🕵️

#1389 Remove unused job "success"
  .github/workflows/ci.yml
Labels: PR type: miscellaneous 👾

#1390 Launch sync-pre-commit only when relevant files were modified
  .pre-commit-config.yaml
Labels: PR type: miscellaneous 👾

#1391 Fix licence, packages and badges
  README.md
  pyproject.toml
Labels: PR type: miscellaneous 👾

#1393 Fix publish workflow by using ref
  .github/workflows/ci.yml
Labels: PR type: miscellaneous 👾

#1395 Remove duplicate GitHub Action benchmark workflow
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
Labels: PR type: miscellaneous 👾

#1399 Remove rogue debug print()
  procrastinate/contrib/django/django_connector.py
Labels: PR type: miscellaneous 👾

#1404 Use sync-pre-commit-with-uv
  .pre-commit-config.yaml
  pyproject.toml
  scripts/sync-pre-commit.py
  uv.lock
Labels: PR type: miscellaneous 👾
