Repository procrastinate-org/procrastinate, pull requests merged in 2025-01, with the labels that each got.

#1264 Add devcontainer setup
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: PR type: miscellaneous 👾

#1269 Don't use dropped python version for static type checking
  .github/workflows/ci.yml
Labels: PR type: miscellaneous 👾

#1271 Fix to lowest Python version for static type checking in CI
  .github/workflows/ci.yml
Labels: PR type: miscellaneous 👾

#1278 Update v3 from main branch
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  docker-compose.yml
  docs/howto/basics.md
  docs/howto/basics/windows.md
  docs/howto/django.md
  docs/howto/django/basic_usage.md
  poetry.lock
  procrastinate/cli.py
  procrastinate/contrib/django/management/commands/procrastinate.py
  procrastinate/contrib/django/migrations/0031_add_indexes_for_fetch_job.py
  procrastinate/contrib/django/migrations/0032_pre_cancel_notification.py
  procrastinate/contrib/django/migrations/0033_post_cancel_notification.py
  procrastinate/contrib/django/procrastinate_app.py
  procrastinate/signals.py
  procrastinate/sql/migrations/02.14.01_01_add_indexes_for_fetch_job.sql
  procrastinate/sql/migrations/03.00.00_50_post_cancel_notification.sql
  procrastinate/sql/schema.sql
  pyproject.toml
  tests/acceptance/app.py
  tests/acceptance/test_nominal.py
Labels: PR type: miscellaneous 👾

#1277 Improve devcontainer setup
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/post-create.sh
  CONTRIBUTING.md
Labels: PR type: miscellaneous 👾

#1283 Add task back as a property on job context
  docs/howto/advanced/retry.md
  docs/reference.rst
  procrastinate/job_context.py
  tests/unit/test_job_context.py
Labels: PR type: feature ⭐️

#1031 docs: add structlog config
  docs/howto/production/logging.md
Labels: PR type: documentation 📚

#1298 Fix acceptance test when releasing
  noxfile.py
Labels: PR type: miscellaneous 👾

#1294 Switch from Poetry to uv
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  .readthedocs.yml
  CONTRIBUTING.md
  Dockerfile
  dev-env
  docker-compose.yml
  docs/demos.md
  docs/howto/django/configuration.md
  docs/howto/production/logging.md
  noxfile.py
  poetry.lock
  procrastinate/demos/README.md
  procrastinate/demos/__init__.py
  procrastinate/demos/demo_async/__init__.py
  procrastinate/demos/demo_async/__main__.py
  procrastinate/demos/demo_async/app.py
  procrastinate/demos/demo_async/tasks.py
  procrastinate/demos/demo_django/__init__.py
  procrastinate/demos/demo_django/__main__.py
  procrastinate/demos/demo_django/demo/__init__.py
  procrastinate/demos/demo_django/demo/admin.py
  procrastinate/demos/demo_django/demo/apps.py
  procrastinate/demos/demo_django/demo/migrations/0001_initial.py
  procrastinate/demos/demo_django/demo/migrations/__init__.py
  procrastinate/demos/demo_django/demo/models.py
  procrastinate/demos/demo_django/demo/tasks.py
  procrastinate/demos/demo_django/demo/templates/demo/book_form.html
  procrastinate/demos/demo_django/demo/templates/demo/book_list.html
  procrastinate/demos/demo_django/demo/views.py
  procrastinate/demos/demo_django/manage.py
  procrastinate/demos/demo_django/project/__init__.py
  procrastinate/demos/demo_django/project/asgi.py
  procrastinate/demos/demo_django/project/settings.py
  procrastinate/demos/demo_django/project/urls.py
  procrastinate/demos/demo_django/project/wsgi.py
  procrastinate/demos/demo_sync/__init__.py
  procrastinate/demos/demo_sync/__main__.py
  procrastinate/demos/demo_sync/app.py
  procrastinate/demos/demo_sync/tasks.py
  pyproject.toml
  scripts/README.md
  scripts/bootstrap
  scripts/docs
  scripts/sync-pre-commit.py
  scripts/tests
  tests/integration/contrib/sphinx/test-root/index.rst
  tests/unit/test_shell.py
  tests/unit/test_worker_sync.py
  uv.lock
Labels: PR type: miscellaneous 👾

#1299 Add compatibility with Python 3.13
  .devcontainer/Dockerfile
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  README.md
  procrastinate/contrib/django/__init__.py
  pyproject.toml
  tests/acceptance/django_settings.py
  tests/conftest.py
Labels: PR type: feature ⭐️

#1300 Bug in `select_stalled_jobs` sql query
  procrastinate/sql/queries.sql
  tests/integration/test_manager.py
Labels: PR type: bugfix 🕵️

#1303 uv manages to understand it needs to differentiate the django version depending on python
  docs/howto/django/configuration.md
  pyproject.toml
  scripts/sync-pre-commit.py
  uv.lock
Labels: PR type: miscellaneous 👾

#1306 Older PG compat
  .github/workflows/ci.yml
  README.md
  procrastinate/sql/migrations/03.00.00_01_pre_cancel_notification.sql
  procrastinate/sql/schema.sql
Labels: PR type: bugfix 🕵️

#1309 Create FUNDING.yml
  .github/FUNDING.yml
Labels: PR type: miscellaneous 👾

#1311 Fetch tags when releasing
  .github/workflows/ci.yml
Labels: PR type: miscellaneous 👾

#1312 uv-dynamic-versioning needs to know that we don't prefix our tags with `v`
  pyproject.toml
Labels: PR type: miscellaneous 👾
